// AUTH TYPES
export const USER_AUTH_START = "USER_AUTH_START";
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_AUTH_FAILURE = "USER_AUTH_FAILURE";

export const USER_AUTH_INITIATE_LOGOUT = "USER_AUTH_INITIATE_LOGOUT";
export const USER_AUTH_LOGOUT = "USER_AUTH_LOGOUT";
export const USER_AUTH_CHECK_TIMEOUT = "USER_AUTH_CHECK_TIMEOUT";
export const USER_AUTH_CHECK_STATE = "USER_AUTH_CHECK_STATE";

export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_CLEAR_ERROR_MESSAGE = "USER_CLEAR_ERROR_MESSAGE";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const USER_LOG_OUT_MESSAGE = "USER_LOG_OUT_MESSAGE";
export const CLEAR_LOG_OUT_MESSAGE = "CLEAR_LOG_OUT_MESSAGE";

// PASSWORD TYPES
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export const NEW_PASSWORD_UPDATE_REQUEST = "NEW_PASSWORD_UPDATE_REQUEST";
export const NEW_PASSWORD_UPDATE_SUCCESS = "NEW_PASSWORD_UPDATE_SUCCESS";
export const NEW_PASSWORD_UPDATE_FAILURE = "NEW_PASSWORD_UPDATE_FAILURE";

//USER TYPES
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";
export const CLEAR_USER_ERROR_MESSAGE = "CLEAR_USER_ERROR_MESSAGE";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_START = "USER_PROFILE_START";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";

export const USER_UPDATE_START = "USER_UPDATE_START";
export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE";

export const GET_USER_ORDERS_REQUEST = "GET_USER_ORDERS_REQUEST";
export const GET_USER_ORDERS_SUCCESS = "GET_USER_ORDERS_SUCCESS";
export const GET_USER_ORDERS_FAILURE = "GET_USER_ORDERS_FAILURE";

export const USER_ORDERS_BY_DATE_REQUEST = "USER_ORDERS_BY_DATE_REQUEST";
export const USER_ORDERS_BY_DATE_SUCCESS = "USER_ORDERS_BY_DATE_SUCCESS";
export const USER_ORDERS_BY_DATE_FAILURE = "USER_ORDERS_BY_DATE_FAILURE";

export const CHANGE_USER_PRODUCTS = "CHANGE_USER_PRODUCTS";

//USER MESSAGE TYPES
export const USER_MESSAGES_REQUEST = "USER_MESSAGES_REQUEST";
export const USER_MESSAGES_SUCCESS = "USER_MESSAGES_SUCCESS";
export const USER_MESSAGES_FAILURE = "USER_MESSAGES_FAILURE";

export const USER_SEEN_MESSAGE_REQUEST = "USER_SEEN_MESSAGE_REQUEST";
export const USER_SEEN_MESSAGE_SUCCESS = "USER_SEEN_MESSAGE_SUCCESS";
export const USER_SEEN_MESSAGE_FAILURE = "USER_SEEN_MESSAGE_FAILURE";

export const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAILURE = "DELETE_MESSAGE_FAILURE";

//USER SOLD ITEMS
export const GET_USER_SOLD_ITEMS_REQUEST = "GET_USER_SOLD_ITEMS_REQUEST";
export const GET_USER_SOLD_ITEMS_SUCCESS = "GET_USER_SOLD_ITEMS_SUCCESS";
export const GET_USER_SOLD_ITEMS_FAILURE = "GET_USER_SOLD_ITEMS_FAILURE";

// SHOPPING CART ACTION TYPES
export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILURE = "GET_CART_FAILURE";

export const ADD_PRODUCT_QUANTITY = "ADD_PRODUCT_QUANTITY";
export const REMOVE_PRODUCT_QUANTITY = "REMOVE_PRODUCT_QUANTITY";

export const SET_PRODUCT_QUANTITY_REQUEST = "SET_PRODUCT_QUANTITY_REQUEST";
export const SET_PRODUCT_QUANTITY_SUCCESS = "SET_PRODUCT_QUANTITY_SUCCESS";
export const SET_PRODUCT_QUANTITY_FAILURE = "SET_PRODUCT_QUANTITY_FAILURE";

export const DELETE_FROM_CART_REQUEST = "DELETE_FROM_CART_REQUEST";
export const DELETE_FROM_CART_SUCCESS = "DELETE_FROM_CART_SUCCESS";
export const DELETE_FROM_CART_FAILURE = "DELETE_FROM_CART_FAILURE";

export const SET_TOTAL_SUMMARY_REQUEST = "SET_TOTAL_SUMMARY_REQUEST";
export const SET_TOTAL_SUMMARY_SUCCESS = "SET_TOTAL_SUMMARY_SUCCESS";
export const SET_TOTAL_SUMMARY_FAILURE = "SET_TOTAL_SUMMARY_FAILURE";

export const ADD_TO_CART_START = "ADD_TO_CART_START";
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

export const CLEAR_CART_ERROR_MESSAGE = "CLEAR_CART_ERROR_MESSAGE";

// PRODUCT ACTION TYPES
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";
export const CLEAR_PRODUCT_FAILURE = "CLEAR_PRODUCT_FAILURE";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";
export const CLEAR_UPDATE_PRODUCT_FAILURE = "CLEAR_UPDATE_PRODUCT_FAILURE";

export const GET_USER_PRODUCTS_REQUEST = "GET_USER_PRODUCTS_REQUEST";
export const GET_USER_PRODUCTS_SUCCESS = "GET_USER_PRODUCTS_SUCCESS";
export const GET_USER_PRODUCTS_FAILURE = "GET_USER_PRODUCTS_FAILURE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const ON_CHANGE_INPUT_SEARCH = "ON_CHANGE_INPUT_SEARCH";

// SEARCH ACTION TYPES
export const FIND_PRODUCTS_BY_TITLE_REQUEST = "FIND_PRODUCTS_BY_TITLE_REQUEST";
export const FIND_PRODUCTS_BY_TITLE_SUCCESS = "FIND_PRODUCTS_BY_TITLE_SUCCESS";
export const FIND_PRODUCTS_BY_TITLE_FAILURE = "FIND_PRODUCTS_BY_TITLE_FAILURE";

export const ON_CHANGE_CATEGORY_SEARCH = "ON_CHANGE_CATEGORY_SEARCH";

export const FIND_PRODUCT_BY_CATEGORY_REQUEST =
  "FIND_PRODUCT_BY_CATEGORY_REQUEST";
export const FIND_PRODUCT_BY_CATEGORY_SUCCESS =
  "FIND_PRODUCT_BY_CATEGORY_SUCCESS";
export const FIND_PRODUCT_BY_CATEGORY_FAILURE =
  "FIND_PRODUCT_BY_CATEGORY_FAILURE";

// ORDER ACTION TYPES

export const SET_ORDER_REQUEST = "SET_ORDER_REQUEST";
export const SET_ORDER_SUCCESS = "SET_ORDER_SUCCESS";
export const SET_ORDER_FAILURE = "SET_ORDER_FAILURE";

export const ADD_ORDER_REQUEST = "ADD_ORDER_REQUEST";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAILURE = "ADD_ORDER_FAILURE";

export const REMOVE_ITEMS_FROM_CART_REQUEST = "REMOVE_ITEMS_FROM_CART_REQUEST";
export const REMOVE_ITEMS_FROM_CART_SUCCESS = "REMOVE_ITEMS_FROM_CART_SUCCESS";
export const REMOVE_ITEMS_FROM_CART_FAILURE = "REMOVE_ITEMS_FROM_CART_FAILURE";

export const REMOVE_PRODUCTS_FROM_CART_REQUEST =
  "REMOVE_PRODUCTS_FROM_CART_REQUEST";

export const SET_ORDER_REDIRECT_PATH = "SET_ORDER_REDIRECT_PATH";

// CATEGORY ACTION TYPES
export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";
export const CLEAR_CATEGORIES_FAILURE = "CLEAR_CATEGORIES_FAILURE";

// ADMIN ACTION TYPES
export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";

export const DELETE_PRODUCTS_REQUEST = "DELETE_PRODUCTS_REQUEST";
export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS";
export const DELETE_PRODUCTS_FAILURE = "DELETE_PRODUCTS_FAILURE";

export const GET_GLOBAL_DATA_REQUEST = "GET_GLOBAL_DATA_REQUEST";
export const GET_GLOBAL_DATA_SUCCESS = "GET_GLOBAL_DATA_SUCCESS";
export const GET_GLOBAL_DATA_FAILURE = "GET_GLOBAL_DATA_FAILURE";

export const UPDATE_VAT_RATE_REQUEST = "UPDATE_VAT_RATE_REQUEST";
export const UPDATE_VAT_RATE_SUCCESS = "UPDATE_VAT_RATE_SUCCESS";
export const UPDATE_VAT_RATE_FAILURE = "UPDATE_VAT_RATE_FAILURE";

export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAILURE = "GET_ALL_PRODUCTS_FAILURE";

export const GET_ORDERS_BY_DATE_REQUEST = "GET_ORDERS_BY_DATE_REQUEST";
export const GET_ORDERS_BY_DATE_SUCCESS = "GET_ORDERS_BY_DATE_SUCCESS";
export const GET_ORDERS_BY_DATE_FAILURE = "GET_ORDERS_BY_DATE_FAILURE";
export const CLEAR_ORDERS_BY_DATE_ERROR = "CLEAR_ORDERS_BY_DATE_ERROR";

export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAILURE = "GET_ALL_ORDERS_FAILURE";

export const GET_ORDERS_BY_USER_NAME_REQUEST =
  "GET_ORDERS_BY_USER_NAME_REQUEST";
export const GET_ORDERS_BY_USER_NAME_SUCCESS =
  "GET_ORDERS_BY_USER_NAME_SUCCESS";
export const GET_ORDERS_BY_USER_NAME_FAILURE =
  "GET_ORDERS_BY_USER_NAME_FAILURE";

export const CHANGE_PRODUCT_STATUS_START = "CHANGE_PRODUCT_STATUS_START";
export const CHANGE_PRODUCT_STATUS_SUCCESS = "CHANGE_PRODUCT_STATUS_SUCCESS";
export const CHANGE_PRODUCT_STATUS_FAILURE = "CHANGE_PRODUCT_STATUS_FAILURE";
